# -*- coding: utf-8 -*-
"""Neural.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fA3wwDsiLOb2bxkOA0V8xTvlK_EilVIX
"""

import torch
import torch.nn as nn

model=nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

